// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package pixellab

import (
	"context"
	"encoding/json/v2"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "Pixel Lab API"

var defaultBaseURL = &url.URL{
	Scheme: "",
	Host:   "",
	Path:   "/v1",
}

// Client is an HTTP client for the pixellab API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	for _, opt := range opts {
		opt(c)
	}

	return c, nil
}

// Creates a pixel art image based on the provided parameters. Called "Create image (new)" in the plugin.
//
// Supported image size:
// - Minimum area 32x32 and maximum area 400x400
//
// Supported features:
// - Init image
// - Forced palette
// - Transparent background
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.generate_image_pixflux(
//
//	description="cute dragon",
//	image_size=dict(width=128, height=128),
//
// )
// response.image.pil_image()
// ```
//
//	POST /generate-image-pixflux
func (c *Client) GenerateImagePixflux(ctx context.Context, body GenerateImagePixfluxRequest) (*GenerateImagePixfluxResponse, error) {
	return GenerateImagePixflux[GenerateImagePixfluxResponse](ctx, c, body)
}

// Creates a pixel art image based on the provided parameters. Called "Create image (new)" in the plugin.
//
// Supported image size:
// - Minimum area 32x32 and maximum area 400x400
//
// Supported features:
// - Init image
// - Forced palette
// - Transparent background
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.generate_image_pixflux(
//
//	description="cute dragon",
//	image_size=dict(width=128, height=128),
//
// )
// response.image.pil_image()
// ```
// You can define a custom result to unmarshal the response into.
//
//	POST /generate-image-pixflux
func GenerateImagePixflux[R any](ctx context.Context, c *Client, body GenerateImagePixfluxRequest) (*R, error) {
	u := c.baseURL.JoinPath("generate-image-pixflux")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successfully generated image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Invalid API token
		return nil, fmt.Errorf("GenerateImagePixflux: status %s", rsp.Status)
	case http.StatusPaymentRequired:
		// Insufficient credits
		return nil, fmt.Errorf("GenerateImagePixflux: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Validation error
		return nil, fmt.Errorf("GenerateImagePixflux: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Too many requests
		return nil, fmt.Errorf("GenerateImagePixflux: status %s", rsp.Status)
	case 529:
		// Rate limit exceeded
		return nil, fmt.Errorf("GenerateImagePixflux: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Generates a pixel art image based on the provided parameters. Called "Generate image (style)" in the plugin.
//
// Supported image size:
// - Maximum area 200x200
//
// Supported features:
// - Style image
// - Inpainting
// - Init image
// - Forced palette
// - Transparent background
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.generate_image_bitforge(
//
//	description="cute dragon",
//	image_size=dict(width=128, height=128),
//
// )
// response.image.pil_image()
// ```
//
//	POST /generate-image-bitforge
func (c *Client) GenerateImageBitforge(ctx context.Context, body GenerateImageBitforgeRequest) (*GenerateImageBitforgeResponse, error) {
	return GenerateImageBitforge[GenerateImageBitforgeResponse](ctx, c, body)
}

// Generates a pixel art image based on the provided parameters. Called "Generate image (style)" in the plugin.
//
// Supported image size:
// - Maximum area 200x200
//
// Supported features:
// - Style image
// - Inpainting
// - Init image
// - Forced palette
// - Transparent background
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.generate_image_bitforge(
//
//	description="cute dragon",
//	image_size=dict(width=128, height=128),
//
// )
// response.image.pil_image()
// ```
// You can define a custom result to unmarshal the response into.
//
//	POST /generate-image-bitforge
func GenerateImageBitforge[R any](ctx context.Context, c *Client, body GenerateImageBitforgeRequest) (*R, error) {
	u := c.baseURL.JoinPath("generate-image-bitforge")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successfully generated image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Invalid API token
		return nil, fmt.Errorf("GenerateImageBitforge: status %s", rsp.Status)
	case http.StatusPaymentRequired:
		// Insufficient credits
		return nil, fmt.Errorf("GenerateImageBitforge: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Validation error
		return nil, fmt.Errorf("GenerateImageBitforge: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Too many requests
		return nil, fmt.Errorf("GenerateImageBitforge: status %s", rsp.Status)
	case 529:
		// Rate limit exceeded
		return nil, fmt.Errorf("GenerateImageBitforge: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Creates a pixel art animation based on the provided parameters. Called "Animate with skeleton" in the plugin.
//
// Supported image sizes:
// - 16x16
// - 32x32
// - 64x64
// - 128x128
// - 256x256
//
// Supported features:
// - Inpainting
// - Init image
// - Forced palette
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.animate_with_skeleton(
//
//	view="side",
//	direction="south",
//	image_size=dict(width=64, height=64),
//	reference_image=reference_image,
//	inpainting_images=existing_animation_frames,
//	mask_images=mask_images,
//	skeleton_keypoints=skeleton_keypoints,
//
// )
// images = [image.pil_image() for image in response.images]
// ```
//
//	POST /animate-with-skeleton
func (c *Client) AnimateWithSkeleton(ctx context.Context, body AnimateWithSkeletonRequest) (*AnimateWithSkeletonResponse, error) {
	return AnimateWithSkeleton[AnimateWithSkeletonResponse](ctx, c, body)
}

// Creates a pixel art animation based on the provided parameters. Called "Animate with skeleton" in the plugin.
//
// Supported image sizes:
// - 16x16
// - 32x32
// - 64x64
// - 128x128
// - 256x256
//
// Supported features:
// - Inpainting
// - Init image
// - Forced palette
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.animate_with_skeleton(
//
//	view="side",
//	direction="south",
//	image_size=dict(width=64, height=64),
//	reference_image=reference_image,
//	inpainting_images=existing_animation_frames,
//	mask_images=mask_images,
//	skeleton_keypoints=skeleton_keypoints,
//
// )
// images = [image.pil_image() for image in response.images]
// ```
// You can define a custom result to unmarshal the response into.
//
//	POST /animate-with-skeleton
func AnimateWithSkeleton[R any](ctx context.Context, c *Client, body AnimateWithSkeletonRequest) (*R, error) {
	u := c.baseURL.JoinPath("animate-with-skeleton")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successfully generated image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Invalid API token
		return nil, fmt.Errorf("AnimateWithSkeleton: status %s", rsp.Status)
	case http.StatusPaymentRequired:
		// Insufficient credits
		return nil, fmt.Errorf("AnimateWithSkeleton: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Validation error
		return nil, fmt.Errorf("AnimateWithSkeleton: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Too many requests
		return nil, fmt.Errorf("AnimateWithSkeleton: status %s", rsp.Status)
	case 529:
		// Rate limit exceeded
		return nil, fmt.Errorf("AnimateWithSkeleton: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Creates a pixel art animation based on text description and parameters.
//
// Supported image sizes:
// - 64x64
//
// Supported features:
// - Text-guided animation generation
// - Inpainting
// - Init image
// - Forced palette
// - Multiple frames
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.animate_with_text(
//
//	description="human mage",
//	action="walk",
//	view="side",
//	direction="south",
//	image_size=dict(width=64, height=64),
//	reference_image=reference_image,
//	n_frames=4
//
// )
// images = [image.pil_image() for image in response.images]
// ```
//
//	POST /animate-with-text
func (c *Client) AnimateWithText(ctx context.Context, body AnimateWithTextRequest) (*AnimateWithTextResponse, error) {
	return AnimateWithText[AnimateWithTextResponse](ctx, c, body)
}

// Creates a pixel art animation based on text description and parameters.
//
// Supported image sizes:
// - 64x64
//
// Supported features:
// - Text-guided animation generation
// - Inpainting
// - Init image
// - Forced palette
// - Multiple frames
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.animate_with_text(
//
//	description="human mage",
//	action="walk",
//	view="side",
//	direction="south",
//	image_size=dict(width=64, height=64),
//	reference_image=reference_image,
//	n_frames=4
//
// )
// images = [image.pil_image() for image in response.images]
// ```
// You can define a custom result to unmarshal the response into.
//
//	POST /animate-with-text
func AnimateWithText[R any](ctx context.Context, c *Client, body AnimateWithTextRequest) (*R, error) {
	u := c.baseURL.JoinPath("animate-with-text")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successfully generated animation
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Invalid API token
		return nil, fmt.Errorf("AnimateWithText: status %s", rsp.Status)
	case http.StatusPaymentRequired:
		// Insufficient credits
		return nil, fmt.Errorf("AnimateWithText: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Validation error
		return nil, fmt.Errorf("AnimateWithText: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Too many requests
		return nil, fmt.Errorf("AnimateWithText: status %s", rsp.Status)
	case 529:
		// Rate limit exceeded
		return nil, fmt.Errorf("AnimateWithText: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Rotates a pixel art image based on the provided parameters. Called "Rotate" in the plugin.
//
// Supported image sizes:
// - 16x16
// - 32x32
// - 64x64
// - 128x128
//
// Supported features:
// - Init image
// - Forced palette
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.rotate(
//
//	from_view="side",
//	to_view="side",
//	from_direction="south",
//	to_direction="east",
//	image_size=dict(width=16, height=16),
//	from_image=image_of_subject_facing_south,
//
// )
// response.image.pil_image()
// ```
//
//	POST /rotate
func (c *Client) Rotate(ctx context.Context, body RotateRequest) (*RotateResponse, error) {
	return Rotate[RotateResponse](ctx, c, body)
}

// Rotates a pixel art image based on the provided parameters. Called "Rotate" in the plugin.
//
// Supported image sizes:
// - 16x16
// - 32x32
// - 64x64
// - 128x128
//
// Supported features:
// - Init image
// - Forced palette
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.rotate(
//
//	from_view="side",
//	to_view="side",
//	from_direction="south",
//	to_direction="east",
//	image_size=dict(width=16, height=16),
//	from_image=image_of_subject_facing_south,
//
// )
// response.image.pil_image()
// ```
// You can define a custom result to unmarshal the response into.
//
//	POST /rotate
func Rotate[R any](ctx context.Context, c *Client, body RotateRequest) (*R, error) {
	u := c.baseURL.JoinPath("rotate")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successfully generated image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Invalid API token
		return nil, fmt.Errorf("Rotate: status %s", rsp.Status)
	case http.StatusPaymentRequired:
		// Insufficient credits
		return nil, fmt.Errorf("Rotate: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Validation error
		return nil, fmt.Errorf("Rotate: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Too many requests
		return nil, fmt.Errorf("Rotate: status %s", rsp.Status)
	case 529:
		// Rate limit exceeded
		return nil, fmt.Errorf("Rotate: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Creates a pixel art image based on the provided parameters. Called "Inpaint" in the plugin.
//
// Supported image size:
// - Maximum area 200x200
//
// Supported features:
// - Inpainting
// - Init image
// - Forced palette
// - Transparent background
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.inpaint(
//
//	description="boy with wings",
//	image_size=dict(width=16, height=16),
//	inpainting_image=image_of_boy_without_wings,
//	mask_image=mask_image,
//
// )
// response.image.pil_image()
// ```
//
//	POST /inpaint
func (c *Client) Inpaint(ctx context.Context, body InpaintRequest) (*InpaintResponse, error) {
	return Inpaint[InpaintResponse](ctx, c, body)
}

// Creates a pixel art image based on the provided parameters. Called "Inpaint" in the plugin.
//
// Supported image size:
// - Maximum area 200x200
//
// Supported features:
// - Inpainting
// - Init image
// - Forced palette
// - Transparent background
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.inpaint(
//
//	description="boy with wings",
//	image_size=dict(width=16, height=16),
//	inpainting_image=image_of_boy_without_wings,
//	mask_image=mask_image,
//
// )
// response.image.pil_image()
// ```
// You can define a custom result to unmarshal the response into.
//
//	POST /inpaint
func Inpaint[R any](ctx context.Context, c *Client, body InpaintRequest) (*R, error) {
	u := c.baseURL.JoinPath("inpaint")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successfully generated image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Invalid API token
		return nil, fmt.Errorf("Inpaint: status %s", rsp.Status)
	case http.StatusPaymentRequired:
		// Insufficient credits
		return nil, fmt.Errorf("Inpaint: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Validation error
		return nil, fmt.Errorf("Inpaint: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Too many requests
		return nil, fmt.Errorf("Inpaint: status %s", rsp.Status)
	case 529:
		// Rate limit exceeded
		return nil, fmt.Errorf("Inpaint: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Estimates the skeleton of a character, returning a list of keypoints to use with the skeleton animation tool.
//
// Supported image sizes:
// - 16x16
// - 32x32
// - 64x64
// - 128x128
// - 256x256
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.estimate_skeleton(
//
//	image=image_of_the_character_on_a_transparent_background,
//
// )
// response.keypoints
// ```
//
//	POST /estimate-skeleton
func (c *Client) EstimateSkeleton(ctx context.Context, body EstimateSkeletonRequest) (*EstimateSkeletonResponse, error) {
	return EstimateSkeleton[EstimateSkeletonResponse](ctx, c, body)
}

// Estimates the skeleton of a character, returning a list of keypoints to use with the skeleton animation tool.
//
// Supported image sizes:
// - 16x16
// - 32x32
// - 64x64
// - 128x128
// - 256x256
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
//
// response = client.estimate_skeleton(
//
//	image=image_of_the_character_on_a_transparent_background,
//
// )
// response.keypoints
// ```
// You can define a custom result to unmarshal the response into.
//
//	POST /estimate-skeleton
func EstimateSkeleton[R any](ctx context.Context, c *Client, body EstimateSkeletonRequest) (*R, error) {
	u := c.baseURL.JoinPath("estimate-skeleton")
	pr, pw := io.Pipe()
	req := (&http.Request{
		Header: http.Header{
			"User-Agent":   []string{c.userAgent},
			"Content-Type": []string{"application/json"},
		},
		Host:          u.Host,
		Method:        http.MethodPost,
		Proto:         "HTTP/1.1",
		ProtoMajor:    1,
		ProtoMinor:    1,
		URL:           u,
		Body:          pr,
		ContentLength: -1,
	}).WithContext(ctx)

	go func() { pw.CloseWithError(json.MarshalWrite(pw, body, jsonOpts)) }()
	defer pr.Close()

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successfully generated image
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Invalid API token
		return nil, fmt.Errorf("EstimateSkeleton: status %s", rsp.Status)
	case http.StatusPaymentRequired:
		// Insufficient credits
		return nil, fmt.Errorf("EstimateSkeleton: status %s", rsp.Status)
	case http.StatusUnprocessableEntity:
		// Validation error
		return nil, fmt.Errorf("EstimateSkeleton: status %s", rsp.Status)
	case http.StatusTooManyRequests:
		// Too many requests
		return nil, fmt.Errorf("EstimateSkeleton: status %s", rsp.Status)
	case 529:
		// Rate limit exceeded
		return nil, fmt.Errorf("EstimateSkeleton: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Returns the current balance for your account.
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
// balance = client.get_balance()
// print(f"Current balance: {balance.usd} USD")
// ```
//
//	GET /balance
func (c *Client) GetBalance(ctx context.Context) (*CreditsResponse, error) {
	return GetBalance[CreditsResponse](ctx, c)
}

// Returns the current balance for your account.
//
// Using the Python client:
// ```python
// import pixellab
//
// client = pixellab.Client(secret="YOUR_API_TOKEN")
// balance = client.get_balance()
// print(f"Current balance: {balance.usd} USD")
// ```
// You can define a custom result to unmarshal the response into.
//
//	GET /balance
func GetBalance[R any](ctx context.Context, c *Client) (*R, error) {
	u := c.baseURL.JoinPath("balance")
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Successfully retrieved balance
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// Invalid API token
		return nil, fmt.Errorf("GetBalance: status %s", rsp.Status)
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
