// This file provides tests for the client.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package pixellab

import (
	"encoding/json/jsontext"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"

	"github.com/go-api-libs/api"
)

func newTestServer(t *testing.T, status int) *httptest.Server {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
	}))
	t.Cleanup(srv.Close)
	return srv
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return f(r)
}

func TestClient_Error(t *testing.T) {
	t.Run("GenerateImagePixfluxGenerateImagePixfluxPost", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateImagePixfluxGenerateImagePixfluxPost(t.Context(), GenerateImagePixfluxRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateImagePixfluxGenerateImagePixfluxPost(t.Context(), GenerateImagePixfluxRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateImagePixfluxGenerateImagePixfluxPost(t.Context(), GenerateImagePixfluxRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateImagePixfluxGenerateImagePixfluxPost(t.Context(), GenerateImagePixfluxRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GenerateImageBitforgeGenerateImageBitforgePost", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateImageBitforgeGenerateImageBitforgePost(t.Context(), GenerateImageBitforgeRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateImageBitforgeGenerateImageBitforgePost(t.Context(), GenerateImageBitforgeRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateImageBitforgeGenerateImageBitforgePost(t.Context(), GenerateImageBitforgeRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateImageBitforgeGenerateImageBitforgePost(t.Context(), GenerateImageBitforgeRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("AnimateWithSkeletonAnimateWithSkeletonPost", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.AnimateWithSkeletonAnimateWithSkeletonPost(t.Context(), AnimateWithSkeletonRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.AnimateWithSkeletonAnimateWithSkeletonPost(t.Context(), AnimateWithSkeletonRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.AnimateWithSkeletonAnimateWithSkeletonPost(t.Context(), AnimateWithSkeletonRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.AnimateWithSkeletonAnimateWithSkeletonPost(t.Context(), AnimateWithSkeletonRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("AnimateWithTextAnimateWithTextPost", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.AnimateWithTextAnimateWithTextPost(t.Context(), AnimateWithTextRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.AnimateWithTextAnimateWithTextPost(t.Context(), AnimateWithTextRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.AnimateWithTextAnimateWithTextPost(t.Context(), AnimateWithTextRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.AnimateWithTextAnimateWithTextPost(t.Context(), AnimateWithTextRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GenerateRotationRotatePost", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateRotationRotatePost(t.Context(), RotateRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateRotationRotatePost(t.Context(), RotateRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateRotationRotatePost(t.Context(), RotateRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateRotationRotatePost(t.Context(), RotateRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GenerateInpaintingInpaintPost", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateInpaintingInpaintPost(t.Context(), InpaintRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateInpaintingInpaintPost(t.Context(), InpaintRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateInpaintingInpaintPost(t.Context(), InpaintRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GenerateInpaintingInpaintPost(t.Context(), InpaintRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("EstimateSkeletonEstimateSkeletonPost", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateSkeletonEstimateSkeletonPost(t.Context(), EstimateSkeletonRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateSkeletonEstimateSkeletonPost(t.Context(), EstimateSkeletonRequest{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateSkeletonEstimateSkeletonPost(t.Context(), EstimateSkeletonRequest{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.EstimateSkeletonEstimateSkeletonPost(t.Context(), EstimateSkeletonRequest{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetBalanceBalanceGet", func(t *testing.T) {
		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalanceBalanceGet(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalanceBalanceGet(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalanceBalanceGet(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetBalanceBalanceGet(t.Context()); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.DecodingError", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})
}
