// Code generated by `go run ./main.go`. DO NOT EDIT.

package pixellab

import "fmt"

// NewImageSizeForAnimateWithSkeleton builds the ImageSize for AnimateWithSkeletonRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-256
//   - height: 16-256
func NewImageSizeForAnimateWithSkeleton(width, height int) (ImageSize, error) {
	if width < 16 || width > 256 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 256 pixels, got %d", width)
	}
	if height < 16 || height > 256 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 256 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForEditAnimationV2 builds the ImageSize for EditAnimationV2Request.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-256
//   - height: 16-256
func NewImageSizeForEditAnimationV2(width, height int) (ImageSize, error) {
	if width < 16 || width > 256 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 256 pixels, got %d", width)
	}
	if height < 16 || height > 256 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 256 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForAnimateWithText builds the ImageSize for AnimateWithTextRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: exactly 64
//   - height: exactly 64
func NewImageSizeForAnimateWithText(width, height int) (ImageSize, error) {
	if width != 64 {
		return ImageSize{}, fmt.Errorf("width must be exactly 64 pixels, got %d", width)
	}
	if height != 64 {
		return ImageSize{}, fmt.Errorf("height must be exactly 64 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForCreateCharacterWith4Directions builds the ImageSize for CreateCharacterWith4DirectionsRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-128
//   - height: 16-128
func NewImageSizeForCreateCharacterWith4Directions(width, height int) (ImageSize, error) {
	if width < 16 || width > 128 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 128 pixels, got %d", width)
	}
	if height < 16 || height > 128 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 128 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForCreateCharacterWith8Directions builds the ImageSize for CreateCharacterWith8DirectionsRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-128
//   - height: 16-128
func NewImageSizeForCreateCharacterWith8Directions(width, height int) (ImageSize, error) {
	if width < 16 || width > 128 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 128 pixels, got %d", width)
	}
	if height < 16 || height > 128 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 128 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForInterpolationV2 builds the ImageSize for InterpolationV2Request.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-128
//   - height: 16-128
func NewImageSizeForInterpolationV2(width, height int) (ImageSize, error) {
	if width < 16 || width > 128 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 128 pixels, got %d", width)
	}
	if height < 16 || height > 128 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 128 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForCreateImageBitforge builds the ImageSize for CreateImageBitforgeRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-200
//   - height: 16-200
func NewImageSizeForCreateImageBitforge(width, height int) (ImageSize, error) {
	if width < 16 || width > 200 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 200 pixels, got %d", width)
	}
	if height < 16 || height > 200 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 200 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForInpaint builds the ImageSize for InpaintRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-200
//   - height: 16-200
func NewImageSizeForInpaint(width, height int) (ImageSize, error) {
	if width < 16 || width > 200 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 200 pixels, got %d", width)
	}
	if height < 16 || height > 200 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 200 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewReferenceImageSizeForResize builds the ImageSize for ResizeRequest.ReferenceImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-200
//   - height: 16-200
func NewReferenceImageSizeForResize(width, height int) (ImageSize, error) {
	if width < 16 || width > 200 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 200 pixels, got %d", width)
	}
	if height < 16 || height > 200 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 200 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewTargetSizeForResize builds the ImageSize for ResizeRequest.TargetSize, checking width and height
// against the bounds that request requires:
//   - width: 16-200
//   - height: 16-200
func NewTargetSizeForResize(width, height int) (ImageSize, error) {
	if width < 16 || width > 200 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 200 pixels, got %d", width)
	}
	if height < 16 || height > 200 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 200 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForRotate builds the ImageSize for RotateRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-200
//   - height: 16-200
func NewImageSizeForRotate(width, height int) (ImageSize, error) {
	if width < 16 || width > 200 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 200 pixels, got %d", width)
	}
	if height < 16 || height > 200 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 200 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForCreateImagePixen builds the ImageSize for CreateImagePixenRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-768
//   - height: 16-768
func NewImageSizeForCreateImagePixen(width, height int) (ImageSize, error) {
	if width < 16 || width > 768 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 768 pixels, got %d", width)
	}
	if height < 16 || height > 768 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 768 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForEnhancePixenPrompt builds the ImageSize for EnhancePixenPromptRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-768
//   - height: 16-768
func NewImageSizeForEnhancePixenPrompt(width, height int) (ImageSize, error) {
	if width < 16 || width > 768 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 768 pixels, got %d", width)
	}
	if height < 16 || height > 768 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 768 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForCreateImagePixflux builds the ImageSize for CreateImagePixfluxRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-400
//   - height: 16-400
func NewImageSizeForCreateImagePixflux(width, height int) (ImageSize, error) {
	if width < 16 || width > 400 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 400 pixels, got %d", width)
	}
	if height < 16 || height > 400 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 400 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForEditImage builds the ImageSize for EditImageRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-400
//   - height: 16-400
func NewImageSizeForEditImage(width, height int) (ImageSize, error) {
	if width < 16 || width > 400 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 400 pixels, got %d", width)
	}
	if height < 16 || height > 400 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 400 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForCreateIsometricTile builds the ImageSize for CreateIsometricTileRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-64
//   - height: 16-64
func NewImageSizeForCreateIsometricTile(width, height int) (ImageSize, error) {
	if width < 16 || width > 64 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 64 pixels, got %d", width)
	}
	if height < 16 || height > 64 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 64 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForCreateMapObject builds the ImageSize for CreateMapObjectRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 32-400
//   - height: 32-400
func NewImageSizeForCreateMapObject(width, height int) (ImageSize, error) {
	if width < 32 || width > 400 {
		return ImageSize{}, fmt.Errorf("width must be between 32 and 400 pixels, got %d", width)
	}
	if height < 32 || height > 400 {
		return ImageSize{}, fmt.Errorf("height must be between 32 and 400 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForCreateUIAsset builds the ImageSize for CreateUIAssetRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 192-688
//   - height: 192-688
func NewImageSizeForCreateUIAsset(width, height int) (ImageSize, error) {
	if width < 192 || width > 688 {
		return ImageSize{}, fmt.Errorf("width must be between 192 and 688 pixels, got %d", width)
	}
	if height < 192 || height > 688 {
		return ImageSize{}, fmt.Errorf("height must be between 192 and 688 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForEditImagesV2 builds the ImageSize for EditImagesV2Request.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 32-512
//   - height: 32-512
func NewImageSizeForEditImagesV2(width, height int) (ImageSize, error) {
	if width < 32 || width > 512 {
		return ImageSize{}, fmt.Errorf("width must be between 32 and 512 pixels, got %d", width)
	}
	if height < 32 || height > 512 {
		return ImageSize{}, fmt.Errorf("height must be between 32 and 512 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForGenerateImageV2 builds the ImageSize for GenerateImageV2Request.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-792
//   - height: 16-688
func NewImageSizeForGenerateImageV2(width, height int) (ImageSize, error) {
	if width < 16 || width > 792 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 792 pixels, got %d", width)
	}
	if height < 16 || height > 688 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 688 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForGenerateUIV2 builds the ImageSize for GenerateUIV2Request.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-792
//   - height: 16-688
func NewImageSizeForGenerateUIV2(width, height int) (ImageSize, error) {
	if width < 16 || width > 792 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 792 pixels, got %d", width)
	}
	if height < 16 || height > 688 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 688 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForImageToPixelart builds the ImageSize for ImageToPixelartRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 16-1280
//   - height: 16-1280
func NewImageSizeForImageToPixelart(width, height int) (ImageSize, error) {
	if width < 16 || width > 1280 {
		return ImageSize{}, fmt.Errorf("width must be between 16 and 1280 pixels, got %d", width)
	}
	if height < 16 || height > 1280 {
		return ImageSize{}, fmt.Errorf("height must be between 16 and 1280 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}

// NewImageSizeForRemoveBackground builds the ImageSize for RemoveBackgroundRequest.ImageSize, checking width and height
// against the bounds that request requires:
//   - width: 1-400
//   - height: 1-400
func NewImageSizeForRemoveBackground(width, height int) (ImageSize, error) {
	if width < 1 || width > 400 {
		return ImageSize{}, fmt.Errorf("width must be between 1 and 400 pixels, got %d", width)
	}
	if height < 1 || height > 400 {
		return ImageSize{}, fmt.Errorf("height must be between 1 and 400 pixels, got %d", height)
	}
	return ImageSize{Width: width, Height: height}, nil
}
