// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package pixellab

import (
	"encoding/json/v2"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// Request model for animation using skeleton endpoint
type AnimateWithSkeletonRequest struct {
	ImageSize app__endpoints__external__v1__animate_with_skeleton__ImageSize `json:"image_size"`
	// How closely to follow the reference image and skeleton keypoints
	GuidanceScale *float64 `json:"guidance_scale,omitempty"`
	// Camera view angle (default: side)
	View CameraView `json:"view,omitzero"`
	// Subject direction (default: east)
	Direction Direction `json:"direction,omitzero"`
	// Generate in isometric view
	Isometric bool `json:"isometric,omitempty"`
	// Generate in oblique projection
	ObliqueProjection bool `json:"oblique_projection,omitempty"`
	// Initial images to start the generation from
	InitImages Images `json:"init_images,omitempty"`
	// Strength of the initial image influence
	InitImageStrength *int `json:"init_image_strength,omitempty"`
	// Skeleton pose keypoints. Requires EXACTLY 3 frames — the model is a 3-frame window; other counts are rejected with a 422.
	SkeletonKeypoints []AnimateWithSkeletonRequestSkeletonKeypointsItem `json:"skeleton_keypoints,omitempty"`
	// Reference image
	ReferenceImage Image `json:"reference_image"`
	// Images used for showing the model with connected skeleton
	InpaintingImages AnimateWithSkeletonRequestInpaintingImages `json:"inpainting_images,omitempty"`
	// Inpainting / mask image (black and white image, where the white is where the model should inpaint)
	MaskImages AnimateWithSkeletonRequestMaskImages `json:"mask_images,omitempty"`
	// Forced color palette, image containing colors used for palette
	ColorImage *Image `json:"color_image,omitempty"`
	// Seed decides the starting noise
	Seed *int `json:"seed,omitempty"`
}

// Images used for showing the model with connected skeleton
type AnimateWithSkeletonRequestInpaintingImages []Image

// Inpainting / mask image (black and white image, where the white is where the model should inpaint)
type AnimateWithSkeletonRequestMaskImages []Image

// AnimateWithSkeletonRequestSkeletonKeypointsItem defines a model
type AnimateWithSkeletonRequestSkeletonKeypointsItem []Point

// Request model for animation using text endpoint
type AnimateWithTextRequest struct {
	ImageSize app__endpoints__external__v1__animate_with_text__ImageSize `json:"image_size"`
	// Character description
	Description string `json:"description,omitzero"`
	// Negative prompt to guide what not to generate
	NegativeDescription string `json:"negative_description,omitzero"`
	// Action description
	Action string `json:"action,omitzero"`
	// How closely to follow the text prompts
	TextGuidanceScale *float64 `json:"text_guidance_scale,omitempty"`
	// How closely to follow the reference image
	ImageGuidanceScale *float64 `json:"image_guidance_scale,omitempty"`
	// Length of full animation (the model will always generate 4 frames)
	NFrames *int `json:"n_frames,omitempty"`
	// Starting frame index of the full animation
	StartFrameIndex *int `json:"start_frame_index,omitempty"`
	// Camera view angle (default: side)
	View CameraView `json:"view,omitzero"`
	// Subject direction (default: east)
	Direction Direction `json:"direction,omitzero"`
	// Initial images to start the generation from
	InitImages Images `json:"init_images,omitempty"`
	// Strength of the initial image influence
	InitImageStrength *int `json:"init_image_strength,omitempty"`
	// Reference image
	ReferenceImage Image `json:"reference_image"`
	// Existing animation frames to guide the generation
	InpaintingImages AnimateWithTextRequestInpaintingImages `json:"inpainting_images,omitempty"`
	// Inpainting / mask image (black and white image, where the white is where the model should inpaint)
	MaskImages AnimateWithTextRequestMaskImages `json:"mask_images,omitempty"`
	// Forced color palette, image containing colors used for palette
	ColorImage *Image `json:"color_image,omitempty"`
	// Seed for reproducible results (0 for random)
	Seed *int `json:"seed,omitempty"`
}

// Existing animation frames to guide the generation
type AnimateWithTextRequestInpaintingImages []Image

// Inpainting / mask image (black and white image, where the white is where the model should inpaint)
type AnimateWithTextRequestMaskImages []Image

// CameraView defines a model
type CameraView string

const (
	CameraViewSide        CameraView = "side"
	CameraViewLowTopDown  CameraView = "low top-down"
	CameraViewHighTopDown CameraView = "high top-down"
)

// Valid indicates whether the value is a known member of the CameraView enum.
func (e CameraView) Valid() bool {
	switch e {
	case CameraViewSide, CameraViewLowTopDown, CameraViewHighTopDown:
		return true
	default:
		return false
	}
}

// Response model for credits endpoint
//
// Attributes:
//
//	credits (float): The user's current credit balance
type CreditsResponse struct {
	Type string  `json:"type,omitzero"`
	Usd  float64 `json:"usd"`
}

// Detail defines a model
type Detail string

const (
	DetailLowDetail      Detail = "low detail"
	DetailMediumDetail   Detail = "medium detail"
	DetailHighlyDetailed Detail = "highly detailed"
)

// Valid indicates whether the value is a known member of the Detail enum.
func (e Detail) Valid() bool {
	switch e {
	case DetailLowDetail, DetailMediumDetail, DetailHighlyDetailed:
		return true
	default:
		return false
	}
}

// Direction defines a model
type Direction string

const (
	DirectionNorth     Direction = "north"
	DirectionNorthEast Direction = "north-east"
	DirectionEast      Direction = "east"
	DirectionSouthEast Direction = "south-east"
	DirectionSouth     Direction = "south"
	DirectionSouthWest Direction = "south-west"
	DirectionWest      Direction = "west"
	DirectionNorthWest Direction = "north-west"
)

// Valid indicates whether the value is a known member of the Direction enum.
func (e Direction) Valid() bool {
	switch e {
	case DirectionNorth, DirectionNorthEast, DirectionEast, DirectionSouthEast, DirectionSouth, DirectionSouthWest, DirectionWest, DirectionNorthWest:
		return true
	default:
		return false
	}
}

// Request model for estimate skeleton endpoint
type EstimateSkeletonRequest struct {
	// Image for which to estimate the skeleton
	Image *Image `json:"image,omitempty"`
}

// EstimateSkeletonResponse defines a model
type EstimateSkeletonResponse struct {
	Usage     Usage                             `json:"usage"`
	Keypoints EstimateSkeletonResponseKeypoints `json:"keypoints,omitempty"`
}

// EstimateSkeletonResponseKeypoints defines a model
type EstimateSkeletonResponseKeypoints []Keypoint

// Request model for image generation endpoint
type GenerateImageBitforgeRequest struct {
	// Text description of the image to generate
	Description string `json:"description,omitzero"`
	// Text description of what to avoid in the generated image
	NegativeDescription string                                                          `json:"negative_description,omitzero"`
	ImageSize           app__endpoints__external__v__generate_image_bitforge__ImageSize `json:"image_size"`
	// How closely to follow the text description
	TextGuidanceScale *float64 `json:"text_guidance_scale,omitempty"`
	// (Deprecated)
	ExtraGuidanceScale *float64 `json:"extra_guidance_scale,omitempty"`
	// Strength of the style transfer (0-100). 50 = balanced.
	StyleStrength *int `json:"style_strength,omitempty"`
	// Outline style reference
	Outline Outline `json:"outline,omitzero"`
	// Shading style reference
	Shading Shading `json:"shading,omitzero"`
	// Detail style reference
	Detail Detail `json:"detail,omitzero"`
	// Camera view angle
	View CameraView `json:"view,omitzero"`
	// Subject direction
	Direction Direction `json:"direction,omitzero"`
	// Generate in isometric view
	Isometric bool `json:"isometric,omitempty"`
	// Generate in oblique projection
	ObliqueProjection bool `json:"oblique_projection,omitempty"`
	// Generate with transparent background
	NoBackground bool `json:"no_background,omitempty"`
	// Percentage of the canvas to cover
	CoveragePercentage *float64 `json:"coverage_percentage,omitempty"`
	// Initial image to start from
	InitImage *Image `json:"init_image,omitempty"`
	// Strength of the initial image influence
	InitImageStrength *int `json:"init_image_strength,omitempty"`
	// Reference image for style transfer
	StyleImage *Image `json:"style_image,omitempty"`
	// Reference image which is inpainted
	InpaintingImage *Image `json:"inpainting_image,omitempty"`
	// Inpainting / mask image (black and white image, where the white is where the model should inpaint)
	MaskImage *Image `json:"mask_image,omitempty"`
	// Forced color palette, image containing colors used for palette
	ColorImage *Image `json:"color_image,omitempty"`
	// How closely to follow the skeleton keypoints
	SkeletonGuidanceScale *float64 `json:"skeleton_guidance_scale,omitempty"`
	// Skeleton points. Warning! Sizes that are not 16x16, 32x32 and 64x64 can cause the generations to be lower quality
	SkeletonKeypoints GenerateImageBitforgeRequestSkeletonKeypoints `json:"skeleton_keypoints,omitempty"`
	// Seed decides the starting noise
	Seed *int `json:"seed,omitempty"`
}

// Skeleton points. Warning! Sizes that are not 16x16, 32x32 and 64x64 can cause the generations to be lower quality
type GenerateImageBitforgeRequestSkeletonKeypoints []Point

// Request model for pixflux image generation endpoint
type GenerateImagePixfluxRequest struct {
	// Text description of the image to generate
	Description string `json:"description,omitzero"`
	// (Deprecated)
	NegativeDescription string                                                          `json:"negative_description,omitzero"`
	ImageSize           app__endpoints__external__v1__generate_image_pixflux__ImageSize `json:"image_size"`
	// How closely to follow the text description
	TextGuidanceScale *float64 `json:"text_guidance_scale,omitempty"`
	// Outline style reference (weakly guiding)
	Outline Outline `json:"outline,omitzero"`
	// Shading style reference (weakly guiding)
	Shading Shading `json:"shading,omitzero"`
	// Detail style reference (weakly guiding)
	Detail Detail `json:"detail,omitzero"`
	// Camera view angle (weakly guiding)
	View CameraView `json:"view,omitzero"`
	// Subject direction (weakly guiding)
	Direction Direction `json:"direction,omitzero"`
	// Generate in isometric view (weakly guiding)
	Isometric bool `json:"isometric,omitempty"`
	// Generate with transparent background, (blank background over 200x200 area)
	NoBackground bool `json:"no_background,omitempty"`
	// Initial image to start from
	InitImage *Image `json:"init_image,omitempty"`
	// Strength of the initial image influence
	InitImageStrength *int `json:"init_image_strength,omitempty"`
	// Forced color palette, image containing colors used for palette
	ColorImage *Image `json:"color_image,omitempty"`
	// Seed decides the starting noise
	Seed *int `json:"seed,omitempty"`
}

// A base64 encoded image.
//
// Attributes:
//
//	type (Literal["base64"]): Always "base64" to indicate the image encoding type
//	base64 (str): The base64 encoded image data
type Image struct {
	// Image data type
	Type string `json:"type,omitzero"`
	// Base64 encoded image data
	Base64 string `json:"base64,omitzero"`
}

// ImageResult defines a model
type ImageResult struct {
	Usage Usage `json:"usage"`
	// A base64 encoded image.
	//
	// Attributes:
	//     type (Literal["base64"]): Always "base64" to indicate the image encoding type
	//     base64 (str): The base64 encoded image data
	Image Image `json:"image"`
}

// Images defines a model
type Images []Image

// ImagesResult defines a model
type ImagesResult struct {
	Usage  Usage  `json:"usage"`
	Images Images `json:"images,omitempty"`
}

// Request model for image generation endpoint
type InpaintRequest struct {
	// Text description of the image to generate
	Description string `json:"description,omitzero"`
	// Text description of what to avoid in the generated image
	NegativeDescription string                                                          `json:"negative_description,omitzero"`
	ImageSize           app__endpoints__external__v__generate_image_bitforge__ImageSize `json:"image_size"`
	// How closely to follow the text description
	TextGuidanceScale *float64 `json:"text_guidance_scale,omitempty"`
	// (Deprecated)
	ExtraGuidanceScale *float64 `json:"extra_guidance_scale,omitempty"`
	// Outline style reference
	Outline Outline `json:"outline,omitzero"`
	// Shading style reference
	Shading Shading `json:"shading,omitzero"`
	// Detail style reference
	Detail Detail `json:"detail,omitzero"`
	// Camera view angle
	View CameraView `json:"view,omitzero"`
	// Subject direction
	Direction Direction `json:"direction,omitzero"`
	// Generate in isometric view
	Isometric bool `json:"isometric,omitempty"`
	// Generate in oblique projection
	ObliqueProjection bool `json:"oblique_projection,omitempty"`
	// Generate with transparent background
	NoBackground bool `json:"no_background,omitempty"`
	// Initial image to start from
	InitImage *Image `json:"init_image,omitempty"`
	// Strength of the initial image influence
	InitImageStrength *int `json:"init_image_strength,omitempty"`
	// Reference image which is inpainted
	InpaintingImage Image `json:"inpainting_image"`
	// Inpainting / mask image. (black and white image, where the white is where the model should inpaint).
	MaskImage Image `json:"mask_image"`
	// Forced color palette, image containing colors used for palette
	ColorImage *Image `json:"color_image,omitempty"`
	// Seed decides the starting noise
	Seed *int `json:"seed,omitempty"`
}

// Keypoint defines a model
type Keypoint struct {
	X      float64 `json:"x"`
	Y      float64 `json:"y"`
	Label  string  `json:"label,omitzero"`
	ZIndex float64 `json:"z_index"`
}

// Outline defines a model
type Outline string

const (
	OutlineSingleColorBlackOutline Outline = "single color black outline"
	OutlineSingleColorOutline      Outline = "single color outline"
	OutlineSelectiveOutline        Outline = "selective outline"
	OutlineLineless                Outline = "lineless"
)

// Valid indicates whether the value is a known member of the Outline enum.
func (e Outline) Valid() bool {
	switch e {
	case OutlineSingleColorBlackOutline, OutlineSingleColorOutline, OutlineSelectiveOutline, OutlineLineless:
		return true
	default:
		return false
	}
}

// Point defines a model
type Point struct {
	X      float64       `json:"x"`
	Y      float64       `json:"y"`
	Label  SkeletonLabel `json:"label,omitzero"`
	ZIndex *int          `json:"z_index,omitempty"`
}

// Request model for image generation endpoint
type RotateRequest struct {
	ImageSize app__endpoints__external__v__generate_image_bitforge__ImageSize `json:"image_size"`
	// How closely to follow the reference image
	ImageGuidanceScale *float64 `json:"image_guidance_scale,omitempty"`
	// How many degrees to tilt the subject
	ViewChange *int `json:"view_change,omitempty"`
	// How many degrees to rotate the subject
	DirectionChange *int `json:"direction_change,omitempty"`
	// From camera view angle (default: side)
	FromView CameraView `json:"from_view,omitzero"`
	// To camera view angle (default: side)
	ToView CameraView `json:"to_view,omitzero"`
	// From subject direction (default: south)
	FromDirection Direction `json:"from_direction,omitzero"`
	// From subject direction (default: east)
	ToDirection Direction `json:"to_direction,omitzero"`
	// Generate in isometric view
	Isometric bool `json:"isometric,omitempty"`
	// Generate in oblique projection
	ObliqueProjection bool `json:"oblique_projection,omitempty"`
	// Initial image to start from
	InitImage *Image `json:"init_image,omitempty"`
	// Strength of the initial image influence
	InitImageStrength *int `json:"init_image_strength,omitempty"`
	// Inpainting / mask image. Requires init image! (black and white image, where the white is where the model should inpaint)
	MaskImage *Image `json:"mask_image,omitempty"`
	// Reference image to rotate
	FromImage Image `json:"from_image"`
	// Forced color palette, image containing colors used for palette
	ColorImage *Image `json:"color_image,omitempty"`
	// Seed decides the starting noise
	Seed *int `json:"seed,omitempty"`
}

// Shading defines a model
type Shading string

const (
	ShadingFlatShading           Shading = "flat shading"
	ShadingBasicShading          Shading = "basic shading"
	ShadingMediumShading         Shading = "medium shading"
	ShadingDetailedShading       Shading = "detailed shading"
	ShadingHighlyDetailedShading Shading = "highly detailed shading"
)

// Valid indicates whether the value is a known member of the Shading enum.
func (e Shading) Valid() bool {
	switch e {
	case ShadingFlatShading, ShadingBasicShading, ShadingMediumShading, ShadingDetailedShading, ShadingHighlyDetailedShading:
		return true
	default:
		return false
	}
}

// SkeletonLabel defines a model
type SkeletonLabel string

const (
	SkeletonLabelNose          SkeletonLabel = "NOSE"
	SkeletonLabelNeck          SkeletonLabel = "NECK"
	SkeletonLabelRightShoulder SkeletonLabel = "RIGHT SHOULDER"
	SkeletonLabelRightElbow    SkeletonLabel = "RIGHT ELBOW"
	SkeletonLabelRightArm      SkeletonLabel = "RIGHT ARM"
	SkeletonLabelLeftShoulder  SkeletonLabel = "LEFT SHOULDER"
	SkeletonLabelLeftElbow     SkeletonLabel = "LEFT ELBOW"
	SkeletonLabelLeftArm       SkeletonLabel = "LEFT ARM"
	SkeletonLabelRightHip      SkeletonLabel = "RIGHT HIP"
	SkeletonLabelRightKnee     SkeletonLabel = "RIGHT KNEE"
	SkeletonLabelRightLeg      SkeletonLabel = "RIGHT LEG"
	SkeletonLabelLeftHip       SkeletonLabel = "LEFT HIP"
	SkeletonLabelLeftKnee      SkeletonLabel = "LEFT KNEE"
	SkeletonLabelLeftLeg       SkeletonLabel = "LEFT LEG"
	SkeletonLabelRightEye      SkeletonLabel = "RIGHT EYE"
	SkeletonLabelLeftEye       SkeletonLabel = "LEFT EYE"
	SkeletonLabelRightEar      SkeletonLabel = "RIGHT EAR"
	SkeletonLabelLeftEar       SkeletonLabel = "LEFT EAR"
)

// Valid indicates whether the value is a known member of the SkeletonLabel enum.
func (e SkeletonLabel) Valid() bool {
	switch e {
	case SkeletonLabelNose, SkeletonLabelNeck, SkeletonLabelRightShoulder, SkeletonLabelRightElbow, SkeletonLabelRightArm, SkeletonLabelLeftShoulder, SkeletonLabelLeftElbow, SkeletonLabelLeftArm, SkeletonLabelRightHip, SkeletonLabelRightKnee, SkeletonLabelRightLeg, SkeletonLabelLeftHip, SkeletonLabelLeftKnee, SkeletonLabelLeftLeg, SkeletonLabelRightEye, SkeletonLabelLeftEye, SkeletonLabelRightEar, SkeletonLabelLeftEar:
		return true
	default:
		return false
	}
}

// Usage defines a model
type Usage struct {
	Type        UsageType `json:"type,omitzero"`
	Usd         *float64  `json:"usd,omitempty"`
	Generations *float64  `json:"generations,omitempty"`
}

// UsageType defines a model
type UsageType string

const (
	UsageTypeUsd         UsageType = "usd"
	UsageTypeGenerations UsageType = "generations"
)

// Valid indicates whether the value is a known member of the UsageType enum.
func (e UsageType) Valid() bool {
	switch e {
	case UsageTypeUsd, UsageTypeGenerations:
		return true
	default:
		return false
	}
}

// app__endpoints__external__v1__animate_with_skeleton__ImageSize defines a model
type app__endpoints__external__v1__animate_with_skeleton__ImageSize struct {
	// Image width in pixels
	Width int `json:"width,omitzero"`
	// Image height in pixels
	Height int `json:"height,omitzero"`
}

// app__endpoints__external__v1__animate_with_text__ImageSize defines a model
type app__endpoints__external__v1__animate_with_text__ImageSize struct {
	// Image width in pixels
	Width int `json:"width,omitzero"`
	// Image height in pixels
	Height int `json:"height,omitzero"`
}

// app__endpoints__external__v1__generate_image_pixflux__ImageSize defines a model
type app__endpoints__external__v1__generate_image_pixflux__ImageSize struct {
	// Image width in pixels
	Width int `json:"width,omitzero"`
	// Image height in pixels
	Height int `json:"height,omitzero"`
}

// app__endpoints__external__v__generate_image_bitforge__ImageSize defines a model
type app__endpoints__external__v__generate_image_bitforge__ImageSize struct {
	// Image width in pixels
	Width int `json:"width,omitzero"`
	// Image height in pixels
	Height int `json:"height,omitzero"`
}
